---
  0:
    - 1
    - 2
    - 3
    - 26
  1:
    - 2
    - 3
    - 0
    - 7
  2:
    - 1
    - 3
    - 0
    - 4
    - 14
  3:
    - 1
    - 2
    - 0
    - 4
    - 5
    - 7
    - 11
    - 13
  4:
    - 2
    - 5
    - 3
    - 8
    - 14
    - 16
    - 25
  5:
    - 4
    - 3
    - 8
    - 6
    - 9
    - 10
    - 13
  6:
    - 5
    - 7
    - 9
  7:
    - 1
    - 3
    - 6
  8:
    - 4
    - 5
    - 10
    - 15
  9:
    - 5
    - 6
    - 10
    - 30
  10:
    - 5
    - 8
    - 9
    - 12
    - 30
  11:
    - 3
    - 10
    - 26
  12:
    - 10
    - 15
    - 19
  13:
    - 3
    - 5
  14:
    - 2
    - 4
    - 23
    - 24
    - 25
  15:
    - 8
    - 12
    - 16
    - 17
    - 19
    - 27
    - 28
  16:
    - 4
    - 15
    - 18
    - 25
  17:
    - 15
    - 18
    - 20
  18:
    - 16
    - 17
    - 21
  19:
    - 12
    - 15
    - 20
  20:
    - 17
    - 19
  21:
    - 18
    - 22
    - 25
    - 30
  22:
    - 21
    - 24
    - 25
  23:
    - 14
    - 24
  24:
    - 14
    - 22
    - 23
  25:
    - 4
    - 14
    - 16
    - 18
    - 21
    - 22
  26:
    - 0
    - 11
    - 27
  27:
    - 15
    - 26
  28:
    - 15
    - 29
  29:
    - 28
    - 30
  30:
    - 9
    - 10
    - 21
    - 29


  