---
  0:
    - 1
    - 2
    - 3
  1:
    - 2
    - 3
    - 0
    - 7
  2:
    - 1
    - 3
    - 0
    - 4
    - 14
  3:
    - 1
    - 2
    - 0
    - 4
    - 5
    - 7
    - 11
    - 13
  4:
    - 2
    - 5
    - 3
    - 8
    - 14
  5:
    - 4
    - 3
    - 8
    - 6
    - 9
    - 10
    - 13
  6:
    - 5
    - 7
    - 9
  7:
    - 1
    - 3
    - 6
  8:
    - 4
    - 5
    - 10
    - 15
  9:
    - 5
    - 6
    - 10
  10:
    - 5
    - 8
    - 9
    - 12
  11:
    - 3
    - 10
  12:
    - 10
    - 15
  13:
    - 3
    - 5
  14:
    - 2
    - 4
  15:
    - 8
    - 12

  