---
  0:
    - 1
    - 2
    - 3
  1:
    - 2
    - 3
    - 0
    - 7
  2:
    - 1
    - 3
    - 0
    - 4
  3:
    - 1
    - 2
    - 0
    - 4
    - 5
    - 7
  4:
    - 2
    - 5
    - 3
    - 8
  5:
    - 4
    - 3
    - 8
    - 6
    - 9
    - 10
  6:
    - 5
    - 7
    - 9
  7:
    - 1
    - 3
    - 6
  8:
    - 4
    - 5
    - 10
  9:
    - 5
    - 6
    - 10
  10:
    - 5
    - 8
    - 9

  